import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/NavBar'
import ipodSVG from '../public/ipod.svg'
import jobbme from '../public/jobbme.png'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex bg-camp-green ">
        <div className="container mx-auto border-2 border-red-300">
          <div className=" border-2 border-blue-200">
            <ul className="font-sans text-white text-lg md:text-2xl font-semibold grid grid-cols-4 justify-items-center">
              <li>
                GABE 
              </li>
              <li>
                Work
              </li>
              <li>
                Projects
              </li>
              <li>
                Contact
              </li>
            </ul>
            </div>
            <div className="flex justify-center ">
              <div className="absolute left-50 mx-3 sm:mx-5 top-16 z-10 rounded-xl pt-2 pb-1 px-2 bg-gray-800">
                <Image className="rounded-lg"  src={jobbme} height={300} width={430} />
              </div>
              <div className="">
                <Image src={ipodSVG} height={910} width={500} layout="intrinsic"/>
                </div>
              </div>
        </div>
      </main>
    </div>
  )
}

export default Home
