import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import headShot from '../public/images/headShot.jpg'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gabe Cornejo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="text-center flex justify-center mt-12 md:mt-36">
          <div className="px-10 md:px-10 md:w-1/2">
            <Image className="rounded-full" src={headShot} height={180} width={180} />
            <h1 className="text-2xl text-mac-purple font-bold pb-10">Hi, I'm Gabe.</h1>
            <p className="text-lg text-mac-purple font-bold mb-12">
              I’m a web developer based in California.  I’m currently working away at developing awesome web apps.  In my free time I like to spend time with my family and work on side projects.
            </p>
          </div>
        </div>
      </Layout>
    </div>
  )
}

export default Home
