import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/NavBar'
import ipodSVG from '../public/ipod.svg'
import jobbme from '../public/jobbme.png'
import Layout from '../components/Layout'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
            <div className="flex justify-center mt-14">
              <div className="absolute left-50 mx-3 sm:mx-5 top-52 z-10 rounded-xl pt-2 pb-1 px-2 bg-gray-800">
                <Image className="rounded-lg" src={jobbme} height={300} width={430} />
              </div>
              <div className="">
                <Image src={ipodSVG} height={910} width={500} layout="intrinsic"/>
                </div>
              </div>
      </Layout>
    </div>
  )
}

export default Home
