import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/NavBar'
import jobbme from '../public/images/jobbme.png'
import webWorks from '../public/images/webWorks.png'
import Layout from '../components/Layout'
import IPod from '../components/IPod'
import * as React from 'react';

const Home: NextPage = () => {
    const [image, setImage] = React.useState(jobbme);

    const handleClick = (e) => {
        let rightButton = e.target.id;
        if (rightButton === "path902-8" && image == jobbme) {
            setImage(webWorks)
        } else {
            setImage(jobbme)
        }
    }


    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="flex justify-center mt-5">
                    <div className="absolute left-50 mx-3 sm:mx-5 top-48 z-10 rounded-xl pt-2 pb-1 px-2 bg-gray-800">
                        <Image className="rounded-lg" src={image} height={250} width={350} />
                    </div>
                    <div className="relative">
                       <IPod handleClick={handleClick} />
                    </div>
                </div>
            </Layout>
        </div>
    )
}

export default Home
