import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/NavBar'
import jobbme from '../public/images/jobbme.png'
import webWorks from '../public/images/webWorks.png'
import Layout from '../components/Layout'
import IPod from '../components/IPod'
import * as React from 'react';

const Home: NextPage = () => {
    const [image, setImage] = React.useState(jobbme);

    const handleClick = (e) => {
        let rightButton = e.target.id;
        if (rightButton === "path902-8" && image == jobbme) {
            setImage(webWorks)
        } else {
            setImage(jobbme)
        }
    }


    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="flex justify-center">
                    <div className="grid grid-cols gap-24 lg:grid-cols-2 mt-5 border-2 border-red-500 px-10 w-full">
                        <div className="relative">
                            <div className="relative border-2 border-green-500">
                                <div className="absolute top-10 z-10 rounded-xl pt-2 pb-1 px-2 bg-gray-800 mx-auto">
                                    {image ? <Image className="rounded-lg" src={image} height={430} width={595} /> : <span className="text-white text-2xl">...Loading</span>}
                                </div>
                                <IPod handleClick={handleClick} />
                            </div>
                        </div>
                        <div className="bg-white h-64 rounded-lg">
                            <div className="mt-8 ml-8 text-2xl text-mac-purple font-semibold">
                                Jobbox.me
                            </div>
                        </div>
                    </div>
                </div>
            </Layout>
        </div>
    )
}

export default Home
